import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
    ScoreContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'flex-end'
    },
    rankConatiner:{
        justifyContent:'center',
        alignItems:'center'
    },
    achiveConatiner:{
        borderRadius:50,
        flexDirection:'row',
        paddingHorizontal:25,
        backgroundColor: '#20324A',
        height:42,
        alignItems:'center'
    },
    rankText:{
        fontSize:28,
        color: '#2C8892',
        fontFamily:'PlusJakartaSans-Bold'
    },
    ownRankText:{
        fontSize:12,
        color: '#51668A',
        fontFamily:'Inter-Regular'
    },
    dcoinImag:{
        width:25,
        height:25,
        marginRight:10,
    },
    achivedText:{
        color:'#fff',
        fontFamily:'PlusJakartaSans-Regular',
        fontSize:16
    },
    rankersLederboard:{
        flexDirection:'row',
        height:113,
        borderRadius:15,
        backgroundColor:'#F2FAFA',
        marginTop:150,
    },
    blueCrown:{
        position:'absolute',
        width:40,
        height:32,
        top:-37
    },
    rankersScoreBoad2:{
        height:159,
        borderRadius:30,
        backgroundColor:'#F2FAFA',
        justifyContent:'center',
        alignItems:'center',
        top:-46,
        width:122,
    },
    rankersScoreBoad:{
        flex:1,
        justifyContent:'center',
        alignItems:'center',
    },
    rankerName:{
        fontFamily:'PlusJakartaSans-Bold',
        fontSize:12,
        marginTop:20
    },
    rankerScore:{
        fontSize:16,
        color:'#2C8892',
        fontFamily:'Inter-SemiBold'
    },
    rankerSpeciality:{
        fontSize:10,
        color:'#51668A',
        fontFamily:'Inter-Regular'
    },
    rankerProfile:{
        width:68,
        height:68,
        borderRadius:50
    },
    rankerProfile2:{
        width:82,
        height:82,
        borderRadius:50
    },
    rankerProfileContainer:{
        justifyContent:'center',
        alignItems:'center',
        borderWidth:3,
        borderRadius:50,
        borderColor:'#45B5C0',
        top:-50,
        position:'absolute'
    },
    rankerProfileContainer2:{
        justifyContent:'center',
        alignItems:'center',
        borderWidth:3,
        borderRadius:50,
        borderColor:'#45B5C0',
        top:-60,
        position:'absolute'
    },
    rankedNumberText:{
        position:'absolute',
        transform: [{ rotate: '-45deg'}],
        color:'#fff',
        fontSize:8
    },
    rankedNumber:{
        position:'absolute',
        bottom:-10,
        // right:31.5,
        backgroundColor:'#45B5C0',
        width:17,
        height:17,
        borderRadius:5,
        transform: [{ rotate: '45deg'}],
        justifyContent:'center',
        alignItems:'center',
    },
    columnTitleName:{
        flexDirection:'row',
        justifyContent:'space-between',
        paddingBottom:10
    },
    columnTitleTextContainer:{
        flexDirection:'row'
    },
    TextName:{
        marginLeft:50,
        color:'#51668A',
        fontFamily:'PlusJakartaSans-Regular',
    },
    TextRank:{
        color:'#51668A',
        fontFamily:'PlusJakartaSans-Regular',
    },
    TextDocCoins:{
        color:'#51668A',
        fontFamily:'PlusJakartaSans-Regular',
    },
    progressConatiner:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginBottom:20,
        // borderWidth:1,
        // overflow:'visible',
        position:'relative'
    },
    winsCoins:{
        fontFamily:'Inter-SemiBold',
    },
    progressBar:{
        flex:1,
        marginRight:30
    },
    blackLine:{
        width:7,
        backgroundColor:'#000',
        position:'absolute',
        height:20,
        bottom:-20,
        left:20
    },
    topScorerPerson:{
        position:'absolute',
        // borderWidth:1,
        height:50,
        width:'100%',
        alignItems:'center',
        flexDirection:'row',
        padding:15
    },
    barProfile:{
        width:32,
        height:32,
        borderRadius:50
    },
    userDetailsContainer:{
        marginLeft:50,
        flexDirection:'row',
        alignItems:'center',
        height:50
    },
    userDetailsText:{
        marginLeft:10,
    },
    barPrmaryKey:{
       fontFamily:'Inter-SemiBold',
       fontSize:16
    },
    barName:{
       fontFamily:'PlusJakartaSans-Bold',
       fontSize:12
    },
    barSpeciality:{
       fontFamily:'Inter-Regular',
       fontSize:10,
       color:'#51668A'
    },
    earnButton:{
    backgroundColor:"#2C8892",
       height:45,
       borderRadius:5,
       justifyContent:'center',
       alignItems:'center'
    },
    earnButtonText:{
       color:'#fff',
       fontSize:16,
       fontFamily:'PlusJakartaSans-Bold',
    },
    TotalBalanceContainer:{
       borderWidth:1,
       height:84,
       borderRadius:8,
       borderStyle:'dotted',
       backgroundColor:'#F2FAFA',
       borderColor:'#D5DEED',
       flexDirection:'row',
       justifyContent:'space-between',
       alignItems:"center",
       padding:15,
       marginVertical:5
    },
    ReedemText:{
        color:"#2376E5",
        fontFamily:'Inter-Regular',
    },
    TotalBalanceDcoinImag:{
        height:48,
        width:48,
    },
    DocCoinContainer:{
        flexDirection:'row',
        alignItems:'center',
    },
    totalCoinContainer:{
        marginLeft:10
    },
    totalCoinNumber:{
        fontSize:28,
        fontFamily:'Inter-Regular',
    },
    totalBalanceText:{
        fontSize:12,
        fontFamily:'Inter-Regular',
    },
    activityBonus:{
       height:56,
       borderRadius:8,
       backgroundColor:'#fff',
       borderColor:'#D5DEED',
       flexDirection:'row',
       justifyContent:'space-between',
       alignItems:"center",
       padding:15,
       marginVertical:5
    },
    activityBonusrhs:{
        flexDirection:'row',
        alignItems:'center'
    },
    howmuchYouEarn:{
        fontFamily:'Inter-SemiBold',
    },
    activityBonusTitle:{
        fontFamily:'PlusJakartaSans-Bold',
        color:'#071B36'
    },
    activityBonusSubTitle:{
        color:'#51668A',
        fontFamily:'Inter-Regular',
        fontSize:8
    },
    ActivityRedirect:{
        marginRight:15,
        color:'#2376E5',
        fontFamily:'Inter-Regular',
    },
})