import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
    rewardsContainer:{
        flexDirection:'row',
        backgroundColor:'#fff',
        padding:5,
        borderRadius:7,
    },
    rewardsBtnActive:{
        height:50,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:5,
        width:'99%',
        backgroundColor:'#2C8892'
    },
    rewardsBtnInActive:{
        borderWidth:2,
        height:50,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:5,
        width:'99%',
        backgroundColor:'#e1f3f5',
        borderColor:'#2C8892'

    },
    rewardsTextActive:{
        color:'#fff',
        fontFamily:'Inter-SemiBold',
        fontSize:15
    },
    rewardsTextInActive:{
        color:'#2C8892',
        fontFamily:'Inter-SemiBold',
        fontSize:15
    },
    rewardsBtnsConatiner:{
        height:50,
        flex:1,
        justifyContent:'center',
        alignItems:'center',
        borderRadius:5
    },

    ///--------------------------Redeem Coins ------------------------------
    CoinsContainer:{
        height:95,
        borderWidth:1,
        marginTop:10,
        borderRadius:8,
        borderStyle:'dashed',
        borderColor:'#D5DEED',
        padding:10,
        backgroundColor:'#F2FAFA'
    },
    availableCoins:{
        flexDirection:'row',
        alignItems:'center',
    },
    availableCoinsTitleText:{
        fontSize:16,
        fontFamily:'PlusJakartaSans-Bold'
    },
    availableCoinsText:{
        fontSize:16,
        fontFamily:'PlusJakartaSans-Regular'
    },
    availableHelpText:{
        color:'#51668A',
        marginTop:5
    },
    dcoinImag:{
        width:20,
        height:20,
        marginHorizontal:4
    },
    vouchers:{
        height:180,
        flexBasis:"48%",
        backgroundColor:'#fff',
        padding:10,
        marginTop:15
    },
    vouchersCoins:{
        flexDirection:'row',
    },
    CoinsText:{
        fontFamily:"PlusJakartaSans-Regular"
    },
    voucherImag:{
        width:80,
        height:35,
        marginTop:10,
    },
    voucherMoney:{
        fontSize:25,
        fontFamily:"PlusJakartaSans-Regular"
    },
    voucherRedeem:{
        fontFamily:"Inter-Regular",
        color:'#2376E5'
    },
    voucherCardImg:{
        width:60,
        height:70,
        position:'absolute',
        right:0,
        bottom:0
    },
    voucherContainer:{
        flexDirection:'row',
        flexWrap:'wrap',
        justifyContent:'space-between',
        
    },

     ///--------------------------Voucher History ------------------------------

     VoucherContainer:{
        height:85,
        borderWidth:1,
        marginTop:10,
        borderRadius:8,
        borderStyle:'dashed',
        borderColor:'#D5DEED',
        padding:10,
        backgroundColor:'#F2FAFA',
        flexDirection:'row',
        alignItems:'center'

     },
     coupon1:{
        width:55,
        height:55,
        marginRight:10
     },
     VoucherCount:{
        fontSize:28,
        fontFamily:"PlusJakartaSans-Regular"
     },
     VoucherBalance:{
        fontFamily:"Inter-Regular"
     },
     vouchersHistory:{
        height:180,
        flexBasis:"48%",
        backgroundColor:'#fff',
        padding:10,
        marginTop:15,
        borderRadius:10
     },
     voucherTitle:{
        fontFamily:'Inter-SemiBold',
        marginTop:10
     },
     voucherDescription:{
        fontFamily:'Inter-Regular',
        marginTop:10,
        fontSize:10
     },
        

});